
import * as dotenv from 'dotenv';
import { parse, stringify } from 'yaml'

import {SdkFunction} from '../dist/sdk';
import { Filter } from '../dist/model';
dotenv.config()

const sdk = new SdkFunction()

const listCommand = process.argv

let task : Promise<any> = (async () => {return "no task ran"})()
listCommand.forEach((val, index) => { switch (val) {
case 'vendor': 
	listCommand.forEach((val,index) => { switch(val) {
	case 'list-workers': 
		task = sdk.fetchWorker()
		break; 
	case 'create-session': 
		task = sdk.CreateSession(((): Filter => {
			let id = -1
			let soundcard = "Default Audio Render Device"
			let monitor = "Generic PnP Monitor"

			listCommand.forEach((val,i) => { switch (val) {
				case '--worker-id': 
					id = +listCommand[i + 1]
				break
				case '--monitor': 
					monitor = listCommand[i + 1]
				break
				case '--soundcard': 
					soundcard = listCommand[i + 1]
				break
			}})

			return {
				worker_id: id,
				soudcard_name: soundcard,
				monitor_name: monitor,
			}
		})())

		break; 
	case 'deactivate-session': 
		task = sdk.DeactivateSession(((): number => {
			let id = -1

			listCommand.forEach((val,i) => { switch (val) {
				case '--session-id': 
					id = +listCommand[i + 1]
				break
			}})

			return id
		})())
		break; 
	default:
		break;
	}})
	break;
case '--help': 
	printHelp()
	break;
}});


task?.then((data) => {
	console.log(stringify(data))
})




function printHelp() {
	console.log("NODEJS SDK CLI")
	console.log("required environment (always): 		")
	console.log(" - PROJECT: project id (ex: \"avmvymkexjarplbxwlnj\")		")
	console.log(" - API_KEY: apikey generated by daemon CLI (ex: \"avmvymkexjarplbxwlnj\")		")
	console.log("")
	console.log("A. CLI to do simple tasks, format: ./daemon.exe proxy current")
	console.log(" -vendor		")
	console.log("    -list-workers         (when) list all workers belong to account	")
	console.log("    -create-session       (when) create new worker session	")
	console.log("        --worker-id       (use) daemon vendor create-session --worker-id 12	")
	console.log("        --monior          (use) daemon vendor create-session --monitor \"\\\\.\\DISPLAY1\"	")
	console.log("        --soundcard       (use) daemon vendor create-session --soundcard \"Default Audio Render Device\"     ")
	console.log("    -deactivate-session   (when) deactivate running worker session	")
	console.log("        --session-id      (use) daemon vendor deactivate-session --session-id 12	")
}